### ISSUE TITLE
404 for Install link

### ISSUE THREAD

**Issue by ribose-jeffreylau** [riboseinc/cryptode.com#4]
Going to https://www.cryptode.com/software/cryptode/docs/installation/ would yield a 404 Not Found from S3.

**Comment by strogonoff** [comment]
Fixed in https://github.com/riboseinc/cryptode.com/commit/9c50b306643d37a97d456f14d46045b0ee5bfe0a.

**Comment by ronaldtse** [comment]
Thanks guys!
